### ISSUE TITLE
If the Authorization header is not provided, it will just PASS

### ISSUE THREAD

**Issue by hls-app** [fiboup/edgelibs#5]
Was trying to add this middleware to hono and it did not work by default. All requests just went through like without authorization.

```ts
app.use(
  "*",
  validateFirebaseAuth({
    projectId: "<your_firebase_project_id>",
  })
);
```

Noticed the missing header and once the `Authorization` header is added the requests are getting 401, as they should.

Problem:

| Authorization Value | Expected | Actual |
| ------------------- | -------- | ------ |
| undefined           | 401      | 200    |
| empty               | 401      | 200    |
| Bearer              | 401      | 200    |
| Bearer xxx            | 401      | 401    |

Current workaround is to validate the JWT before passing it to the middleware.

**Comment by hieuhani** [comment]
Hi @hls-app,

I choose this implementation because there are some public route that can be accessed without a bearer token.
This is the current implementation, it only validates user access token when it's in a valid form of a bearer token (Bearer JWT-TOKEN), if it's in a valid form, but expired or invalid signer => 401. If user doesn't send the bearer token, current implementation will ignore.
You can implement your own middleware to check the context value of currentUser to throw an error.
https://github.com/fiboup/edgelibs/blob/main/packages/hono-firebase-auth/src/middleware.ts#L47

I can improve this function by adding an option to throw 401 error.

Thanks,

**Comment by hls-app** [comment]
Thanks @hieuhani 

That means any endpoint can be freely accessed if the client just deletes the header? That does not seem to be secure at all!

If the route has to be public, they should not be calling `validateFirebaseAuth` middleware.

And they can also do so by 

```ts
  app.get('/public', (c) => c.text('Hello everyone 👋 '))

  app.get(
    '/protected',
   validateFirebaseAuth({
      projectId: 'your-app',
    }),
    (c)  => c.text('Hello my people 👋 '))
  )
```

**Comment by hieuhani** [comment]
Yes, you can control the authentication and authorization yourself by adding custom middleware using the current user context variable. Because in most cases you will need to customize the authorization logic (banned user, roles check, age restriction...) where it is heavy on your business requirements. And this middleware is only validating the Firebase user, you might need an extra user management on your database and you might need to map it somewhere.
Anyway I will add a variation for forcing bearer token validation.

**Comment by hls-app** [comment]
I think you are still missing the point. Any endpoint you are "securing" can be accessed by just deleting the header by a client. Security set at the client is not secure at all.

My suggestion is to enforce firebase auth for any routes that is using this middleware.
